### ISSUE TITLE
可以添加应用，但是UETOOL不起作用·

### ISSUE THREAD

**Issue by a3625021990sdo** [zhangke3016/VirtualUETool#3]

**Comment by 252162875** [comment]
没法用，vivo z1 荣耀8都能添加，有悬浮窗但是不知道怎么用，没看到什么效果

**Comment by zhangke3016** [comment]
1. 确保应用有读写手机存储权限
![image](https://user-images.githubusercontent.com/15261987/51952377-4214a900-2473-11e9-8dd9-6b5e308bac32.png)
2. 添加完应用如下操作：
![gifeditor_20190130_095155](https://user-images.githubusercontent.com/15261987/51952806-cca9d800-2474-11e9-91f7-8071f8248884.gif)
3.如还无法显示效果，贴出log报错信息以便处理

**Comment by 252162875** [comment]
权限都开了，我信任这个应用的所有权限了，操作看不出来怎么操作的，反正是有浮窗，浮窗的三个按钮点了也没啥效果，点添加的应用也没啥效果（两个手机都没效果）

**Comment by caironglin** [comment]
小米手机，同样不能显示UETool

**Comment by daiji168** [comment]
我是重启下手机就可以了

**Comment by nicech6** [comment]
这有人能用？什么玩意

**Comment by zhangke3016** [comment]
fixed
