### ISSUE TITLE
小米8青春版可以安装应用，点击没反应

### ISSUE THREAD

**Issue by haonpu** [zhangke3016/VirtualUETool#6]
小米8青春版，第一次安装添加了一个应用，点击布局层级，可以正常使用，把APP关掉以后重新打开能添加应用，但是四个功能：“捕捉控件”布局层级“等四个，点击了以后没有任何反应MIUI10.2,安卓8.1.0

**Comment by maoqis** [comment]
我也出现相同问题，好想是 虚拟的 application 没有回调。定位了半天纠结

**Comment by zhangke3016** [comment]
已修复问题，可更新体验
